version: "3"
services: 
  api-server:
    image: oz-express
    ports: 
      - "5555:5555"
    networks: 
      - mern-app
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    networks: 
      - mern-app
    volumes: 
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge 
volumes: 
  mongo-data:
    driver: local